In [4]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [8]:
#Число пропусков в каждом столбце
print('\nКоличество пропусков')
df.isnull().sum()

Количество пропусков

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#Статистическое описание
print('\nСтатистика:')
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
#Информация о датасете
print('Основная информация')
df.info()

Основная информация
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Группировка по классу и расчет процента выживаемости
df.groupby('Pclass')['Survived'].mean() * 100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [9]:
#Выведите самое популярное мужское и самое популярное женское имя на корабле

# Фильтрация имен по полу
male_names = df[df['Sex'] == 'male']['Name']
female_names = df[df['Sex'] == 'female']['Name']

# Извлечение имен
male_first_names = male_names.str.extract(r'([^.]*$)')[0]
female_first_names = female_names.str.extract(r'([^.]*$)')[0]

# Поиск самых популярных имен
most_popular_male_name = male_first_names.value_counts().idxmax()
most_popular_female_name = female_first_names.value_counts().idxmax()

# Вывод результата
print(f"Самое популярное мужское имя: {most_popular_male_name}")
print(f"Самое популярное женское имя: {most_popular_female_name}")

Самое популярное мужское имя:  John
Самое популярное женское имя:  Mary

In [10]:
#Самое популярное мужское и женское имя в каждом классе
print("\nСамые популярные имена по классам:")
for pclass in df['Pclass'].unique():
        print(f"\nКласс: {pclass}")
        class_df = df[df['Pclass'] == pclass]

        # Фильтрация имен по полу для текущего класса
        male_names = class_df[class_df['Sex'] == 'male']['Name']
        female_names = class_df[class_df['Sex'] == 'female']['Name']

        # Извлечение имен
        male_first_names = male_names.str.extract(r'([^.]*$)')[0]
        female_first_names = female_names.str.extract(r'([^.]*$)')[0]

        # Поиск самых популярных имен
        most_popular_male_name = male_first_names.value_counts().idxmax() if not male_first_names.empty else "Нет мужских имен"
        most_popular_female_name = female_first_names.value_counts().idxmax() if not female_first_names.empty else "Нет женских имен"

        # Вывод результата
        print("  Самое популярное мужское имя:", most_popular_male_name)
        print("  Самое популярное женское имя:", most_popular_female_name)

Самые популярные имена по классам:

Класс: 3
  Самое популярное мужское имя:  James
  Самое популярное женское имя:  Mary

Класс: 1
  Самое популярное мужское имя:  Victor
  Самое популярное женское имя:  John Bradley (Florence Briggs Thayer)

Класс: 2
  Самое популярное мужское имя:  William John
  Самое популярное женское имя:  Bertha

In [11]:
#Пассажиры старше 44 лет
print("\nПассажиры старше 44 лет:")
print(df[df['Age'] > 44][['Name', 'Age', 'Sex', 'Pclass']])

Пассажиры старше 44 лет:
                                                  Name   Age     Sex  Pclass
6                              McCarthy, Mr. Timothy J  54.0    male       1
11                            Bonnell, Miss. Elizabeth  58.0  female       1
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0  female       2
33                               Wheadon, Mr. Edward H  66.0    male       2
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0  female       1
..                                                 ...   ...     ...     ...
857                             Daly, Mr. Peter Denis   51.0    male       1
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0  female       1
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0  female       1
873                        Vander Cruyssen, Mr. Victor  47.0    male       3
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  female       1

[115 rows x 4 columns]

In [12]:
#Пассажиры младше 44 лет мужского пола
print("\nПассажиры младше 44 лет мужского пола:")
print(df[(df['Age'] < 44) & (df['Sex'] == 'male')][['Name', 'Age', 'Sex', 'Pclass']])

Пассажиры младше 44 лет мужского пола:
                               Name   Age   Sex  Pclass
0           Braund, Mr. Owen Harris  22.0  male       3
4          Allen, Mr. William Henry  35.0  male       3
7    Palsson, Master. Gosta Leonard   2.0  male       3
12   Saundercock, Mr. William Henry  20.0  male       3
13      Andersson, Mr. Anders Johan  39.0  male       3
..                              ...   ...   ...     ...
883   Banfield, Mr. Frederick James  28.0  male       2
884          Sutehall, Mr. Henry Jr  25.0  male       3
886           Montvila, Rev. Juozas  27.0  male       2
889           Behr, Mr. Karl Howell  26.0  male       1
890             Dooley, Mr. Patrick  32.0  male       3

[368 rows x 4 columns]

In [13]:
cabin_counts = df['Cabin'].value_counts()
print("\nКоличество кабин по числу пассажиров:")
for n in [2,3,4]:
  print(f"{n}-местные кабины:", (cabin_counts == n).sum())

Количество кабин по числу пассажиров:
2-местные кабины: 38
3-местные кабины: 5
4-местные кабины: 3